@CarRepairWorkshops_HostAddress = http://localhost:5028



POST {{CarRepairWorkshops_HostAddress}}/api/carRepairWorkshops/{workshopId}/cars/{carId}/repairs
Content-Type: application/json

{
  "DateOfFinalization": "2023-08-15",
  "CarId": 7
}

###

GET {{CarRepairWorkshops.API_HostAddress}}/api/carRepairWorkshops/{WorkshopId}/cars

###

GET {{CarRepairWorkshops.API_HostAddress}}/api/carRepairWorkshops

###
