name: carRepairWorkshops-api-cd

on:
  push:
    branches: 
    -  master
  workflow_dispatch:
  
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with: 
            dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore 
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Publish
        run: dotnet publish ./CarRepairWorkshops/CarRepairWorkshops.API.csproj -o ${{env.DOTNET_ROOT}}/api --no-build 
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.4
        with: 
          name: api-artefact
          path: ${{env.DOTNET_ROOT}}/api

      
  deploy_dev:
    environment: 
      name: 'Dev'
      url: ${{ steps.deploy-to-web-app.outputs.webapp-url }}
    runs-on: ubuntu-latest
    needs: build
    steps: 
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: api-artefact
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v3.0.1
      id: deploy-to-web-app
      with:
        app-name: 'carRepairWorkshops-api-dev'
        publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}

  deploy_prod:
    environment: 
      name: 'Prod'
      url: ${{ steps.prod-to-web-app.outputs.webapp-url }}
    runs-on: ubuntu-latest
    needs: deploy_dev
    steps: 
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: api-artefact
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v3.0.1
      id: prod-to-web-app
      with:
        app-name: 'carRepairWorkshops-api-prod'
        publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}
      
